### ISSUE TITLE
peps_maja_process.py: curl problem on Debian

### ISSUE THREAD

**Issue by aloboa** [olivierhagolle/maja_peps#5]
The following run of peps_maja_process.py on a Debian Buster system using curl 7.6.0 
`$ python ../maja_peps-master/peps_maja_process.py 2 --lonmin -87.38307 --lonmax -86.68346 --latmin 12.19383 --latmax 12.88708 -a ../maja_peps-master/peps.txt -d 2018-10-31 -f 2018-12-31 -p prod_list_gob2018-10-31_2018_12_31.txt`

produces the following error:

```
curl -k -o search.json https://peps.cnes.fr/resto/api/collections/S2ST/search.json?box=-87.38307,12.19383,-86.68346,12.88708\&startDate=2018-10-31\&completionDate=2018-12-31\&maxRecords=500\&productType=S2MSI1C
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (35) error:141A318A:SSL routines:tls_process_ske_dhe:dh key too small
Traceback (most recent call last):
  File "../maja_peps-master/peps_maja_process.py", line 251, in <module>
    prod, download_dict, storage_dict, size_dict = parse_catalog(options.search_json_file)
  File "../maja_peps-master/peps_maja_process.py", line 52, in parse_catalog
    with open(search_json_file) as data_file:
IOError: [Errno 2] No such file or directory: 'search.json'

```
Details on the curl version:

```
$ curl --version
curl 7.64.0 (x86_64-pc-linux-gnu) libcurl/7.64.0 OpenSSL/1.1.1a zlib/1.2.11 libidn2/2.0.5 libpsl/0.20.2 (+libidn2/2.0.4) libssh2/1.8.0 nghttp2/1.32.0 librtmp/2.3
Release-Date: 2019-02-06
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtmp rtsp scp sftp smb smbs smtp smtps telnet tftp 
Features: AsynchDNS IDN IPv6 Largefile GSS-API Kerberos SPNEGO NTLM NTLM_WB SSL libz TLS-SRP HTTP2 UnixSockets HTTPS-proxy PSL 
```

**Comment by aloboa** [comment]
Solved (rather circunvented) by following 
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=907788

> The remote site in the
> example uses a small DH key [0]. If you can't get owner to upgrade the
> site and want still to access the site I suggest to remove
> CipherString = DEFAULT@SECLEVEL=2
> from /etc/ssl/openssl.cnf.
