### ISSUE TITLE
peps_maja_download.py: local variable 'json_url' referenced before assignment

### ISSUE THREAD

**Issue by aloboa** [olivierhagolle/maja_peps#6]
Got an error at running peps_maja_download.py:
```
$ python ../maja_peps-master/peps_maja_download.py -p prod_list_gob2018-10-31_2018_12_01.txt -a ../maja_peps-master/peps.txt 
('wpsId: ', '8e99b3de-3f20-11e9-81a5-0242ac110002')
curl -o ./update_S2A_MSIL1C_20181130T160621_N0207_R097_T16PEV_20181130T193535.txt -k -u  "agustin.lobo@ictja.csic.es:***" https://peps.cnes.fr/resto/wps/outputs/pywps-8e99b3de-3f20-11e9-81a5-0242ac110002.xml
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
Traceback (most recent call last):
  File "../maja_peps-master/peps_maja_download.py", line 139, in <module>
    json_url = parse_update(update_prod)
  File "../maja_peps-master/peps_maja_download.py", line 42, in parse_update
    return json_url
UnboundLocalError: local variable 'json_url' referenced before assignment
```

**Comment by aloboa** [comment]
It seems this was actually related to a problem with the peps service: could not download through the web service either but few hours later both the script and the interactive download work.
I keep the ticket open because the error message needs clarification.

**Comment by olivierhagolle** [comment]
Thanks, I just updated the code to catch the issue. I did not test it much, though, as PEPS is working these days. 
Olivier
